# Generated by Django 5.1 on 2024-08-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_newsarticle_datetime_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='datetime_format',
            field=models.CharField(max_length=100),
        ),
    ]
